export const ACCOUNTS_ENTITY = {
  FINANCIAL_YEAR: 'FINANCIAL_YEAR',
  ACCOUNT_GROUP: 'ACCOUNT_GROUP',
  LEDGER_ACCOUNT: 'LEDGER_ACCOUNT',
  COST_CENTER: 'COST_CENTER',
  VOUCHER: 'VOUCHER',
  VOUCHER_ATTACHMENT: 'VOUCHER_ATTACHMENT',
  ACCOUNT_MAPPING: 'ACCOUNT_MAPPING',
} as const;
